apiVersion: v1
kind: Secret
metadata:
  name: geoservercloud-tls
  namespace: geoserver-cloud
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    REPLACE_WITH_TLS_CERT
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    REPLACE_WITH_TLS_KEY
    -----END PRIVATE KEY-----
