apiVersion: v1
kind: Secret
metadata:
  name: gs-cloud-rabbitmq
  namespace: geoserver-cloud
type: Opaque
stringData:
  host: rmq-rabbitmq.geoserver-cloud.svc.cluster.local
  port: "5672"
  username: geoserver
  password: REPLACE_ME
  vhost: /
