apiVersion: v1
kind: Secret
metadata:
  name: pg-auth
  namespace: geoserver-cloud
type: Opaque
stringData:
  postgres-password: REPLACE_POSTGRES_ADMIN_PASSWORD
  password: REPLACE_GEOSERVER_DB_USER_PASSWORD
