apiVersion: v1
kind: Secret
metadata:
  name: gs-cloud-jdbc-db
  namespace: geoserver-cloud
type: Opaque
stringData:
  hostname: pg-postgresql.geoserver-cloud.svc.cluster.local
  port: "5432"
  database: geoserver
  schema: pgconfig
  username: geoserver
  password: REPLACE_GEOSERVER_DB_USER_PASSWORD
