env: &common-env
  RABBITMQ_HOST:
    type: secret
    name: gs-cloud-rabbitmq
    key: host
  RABBITMQ_PORT:
    type: secret
    name: gs-cloud-rabbitmq
    key: port
  RABBITMQ_USER:
    type: secret
    name: gs-cloud-rabbitmq
    key: username
  RABBITMQ_PASSWORD:
    type: secret
    name: gs-cloud-rabbitmq
    key: password
  JDBCCONFIG_HOST:
    type: secret
    name: gs-cloud-jdbc-db
    key: hostname
  JDBCCONFIG_PORT:
    type: secret
    name: gs-cloud-jdbc-db
    key: port
  JDBCCONFIG_DATABASE:
    type: secret
    name: gs-cloud-jdbc-db
    key: database
  JDBCCONFIG_SCHEMA:
    type: secret
    name: gs-cloud-jdbc-db
    key: schema
  JDBCCONFIG_USERNAME:
    type: secret
    name: gs-cloud-jdbc-db
    key: username
  JDBCCONFIG_PASSWORD:
    type: secret
    name: gs-cloud-jdbc-db
    key: password
  GEOSERVER_SECURITY_ENVIRONMENT_ADMIN_USERNAME:
    type: secret
    name: gs-cloud-admin
    key: username
  GEOSERVER_SECURITY_ENVIRONMENT_ADMIN_PASSWORD:
    type: secret
    name: gs-cloud-admin
    key: password
